[platformio]
src_dir = src
include_dir = include

[env:sticks3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
build_flags =
  -D VIBE_STICK_FIRMWARE_VERSION=\"0.2.0\"
